spring:
  application:
    name: autocenter
  datasource:
    url: jdbc:mysql://localhost:3306/autocenter?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30  # Maximum number of connections in the connection pool

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none  # Options: none, update, create, create-drop
    show-sql: true  # Optional, logs SQL queries
    properties:
      jakarta:
        persistence:
          sharedCache:
            # Entities are not cached unless explicitly marked as cacheable (with the @Cacheable annotation).
            mode: ENABLE_SELECTIVE
      hibernate:
        generate_statistics: true
        cache:
          infinispan:
            # Force using local configuration when only using a single node.
            # Otherwise, a clustered configuration is loaded.
            cfg: org/infinispan/hibernate/cache/commons/builder/infinispan-configs-local.xml
          region:
            # Use Infinispan second level cache provider
            factory_class: infinispan
          use_query_cache: true
          use_second_level_cache: true
        format_sql: true  # Optional, formats SQL queries for readability

  flyway:
    #locations: "classpath:db/migration,db/testdata"
    locations: "classpath:db/migration"