spring:
  application:
    name: autocenter
  datasource:
    url: jdbc:mysql://localhost:3306/autocenter?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30  # Maximum number of connections in the connection pool

  jpa:
    hibernate:
      ddl-auto: none  # Options: none, update, create, create-drop
    show-sql: true  # Optional, logs SQL queries
    properties:
      hibernate:
        format_sql: true  # Optional, formats SQL queries for readability
    database-platform: org.hibernate.dialect.MySQL8Dialect  # Dialect for MySQL 8

  flyway:
    locations: "classpath:db/migration,db/testdata"
    #locations: "classpath:db/migration"