package com.drivelab.autocenter.domain;

public final class NotGeneratedInternalId extends InternalId {
    @Override
    public Long value() {
        throw new UnsupportedOperationException("Id is not yet generated by storage mechanism");
    }

    @Override
    public boolean generated() {
        return false;
    }
}
